import { navigate } from './router.js';
import { getTheme, toggleTheme } from './theme.js';
import { apiDefinitions } from './apis/registry.js';
import { BASE_URL, esc, icon, refreshIcons, copyText } from './utils.js';

export function renderNavbar(path) {
  const isDocs = path === '/docs' || path.startsWith('/docs/');
  return `<header class="sticky top-0 z-40 border-b border-slate-200/80 bg-white/85 backdrop-blur-xl dark:border-slate-800/80 dark:bg-slate-950/85">
    <div class="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 sm:px-8">
      <button data-nav="/" class="group flex items-center gap-3" aria-label="SamApi home"><span class="relative flex h-9 w-9 items-center justify-center rounded-xl bg-slate-950 text-white shadow-lg shadow-slate-950/20 transition-transform group-hover:scale-105 dark:bg-white dark:text-slate-950">${icon('Zap','h-4 w-4 fill-current')}</span><span class="text-[17px] font-bold tracking-[-0.03em] text-slate-950 dark:text-white">Sam<span class="text-cyan-500">Api</span></span></button>
      <nav class="hidden items-center gap-1 md:flex">
        <button data-nav="/" class="rounded-lg px-4 py-2 text-sm font-medium transition-colors ${path === '/' ? 'text-slate-950 dark:text-white' : 'text-slate-500 hover:text-slate-950 dark:text-slate-400 dark:hover:text-white'}">Home</button>
        <div class="relative"><button id="api-menu-btn" class="flex items-center gap-1 rounded-lg px-4 py-2 text-sm font-medium transition-colors ${isDocs ? 'text-slate-950 dark:text-white' : 'text-slate-500 hover:text-slate-950 dark:text-slate-400 dark:hover:text-white'}">APIs ${icon('ChevronDown','h-3.5 w-3.5')}</button><div id="api-menu" class="absolute left-0 top-11 hidden w-48 rounded-xl border border-slate-200 bg-white p-1.5 shadow-xl shadow-slate-950/10 dark:border-slate-800 dark:bg-slate-900"><button data-nav="/docs" class="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-sm text-slate-600 hover:bg-slate-50 dark:text-slate-300 dark:hover:bg-slate-800">${icon('BookOpen','h-4 w-4 text-cyan-500')} All APIs</button><button data-nav="/docs/instagram" class="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-sm text-slate-600 hover:bg-slate-50 dark:text-slate-300 dark:hover:bg-slate-800">${icon('Activity','h-4 w-4 text-cyan-500')} Popular APIs</button></div></div>
        <button data-nav="/docs" class="rounded-lg px-4 py-2 text-sm font-medium transition-colors ${isDocs ? 'text-slate-950 dark:text-white' : 'text-slate-500 hover:text-slate-950 dark:text-slate-400 dark:hover:text-white'}">Documentation</button>
      </nav>
      <div class="hidden items-center gap-3 md:flex"><div class="flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 dark:border-emerald-900/60 dark:bg-emerald-950/30"><span class="relative flex h-2 w-2"><span class="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-75"></span><span class="relative inline-flex h-2 w-2 rounded-full bg-emerald-500"></span></span><span class="text-xs font-semibold text-emerald-700 dark:text-emerald-400">API Online</span></div><button id="theme-btn" class="flex h-9 w-9 items-center justify-center rounded-lg text-slate-500 transition-colors hover:bg-slate-100 hover:text-slate-950 dark:text-slate-400 dark:hover:bg-slate-800 dark:hover:text-white" aria-label="Toggle color theme">${icon(getTheme() === 'dark' ? 'Sun' : 'Moon','h-[17px] w-[17px]')}</button><button data-nav="/docs" class="rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white shadow-sm transition-all hover:-translate-y-0.5 hover:bg-slate-800 dark:bg-white dark:text-slate-950 dark:hover:bg-slate-200">Get started</button></div>
      <button id="mobile-menu-btn" class="flex h-10 w-10 items-center justify-center rounded-lg text-slate-600 md:hidden dark:text-slate-300" aria-label="Toggle menu">${icon('Menu','h-5 w-5')}</button>
    </div>
    <div id="mobile-menu" class="hidden border-t border-slate-200 bg-white px-5 pb-5 pt-3 dark:border-slate-800 dark:bg-slate-950 md:hidden"><div class="flex flex-col gap-1"><button data-nav="/" class="rounded-lg px-3 py-3 text-left text-sm font-medium text-slate-600 dark:text-slate-300">Home</button><button data-nav="/docs" class="rounded-lg px-3 py-3 text-left text-sm font-medium text-slate-600 dark:text-slate-300">Documentation</button><div class="mt-3 flex items-center justify-between border-t border-slate-100 pt-4 dark:border-slate-800"><div class="flex items-center gap-2"><span class="h-2 w-2 rounded-full bg-emerald-500"></span><span class="text-xs font-semibold text-emerald-600">API Online</span></div><button id="mobile-theme-btn" class="flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400">${icon(getTheme() === 'dark' ? 'Sun' : 'Moon','h-4 w-4')} Theme</button></div></div></div>
  </header>`;
}

export function bindNavbar() {
  document.querySelectorAll('[data-nav]').forEach((el) => el.addEventListener('click', () => navigate(el.dataset.nav)));
  document.getElementById('theme-btn')?.addEventListener('click', () => { toggleTheme(); window.__render(); });
  document.getElementById('mobile-theme-btn')?.addEventListener('click', () => { toggleTheme(); window.__render(); });
  document.getElementById('api-menu-btn')?.addEventListener('click', () => document.getElementById('api-menu')?.classList.toggle('hidden'));
  document.getElementById('mobile-menu-btn')?.addEventListener('click', () => document.getElementById('mobile-menu')?.classList.toggle('hidden'));
}

export function renderFooter() {
  return `<footer class="border-t border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950"><div class="mx-auto max-w-7xl px-5 py-14 sm:px-8"><div class="flex flex-col justify-between gap-10 md:flex-row"><div class="max-w-xs"><button data-nav="/" class="mb-4 flex items-center gap-3"><span class="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-950 text-white dark:bg-white dark:text-slate-950">${icon('Zap','h-4 w-4 fill-current')}</span><span class="text-base font-bold tracking-[-0.03em] text-slate-950 dark:text-white">Sam<span class="text-cyan-500">Api</span></span></button><p class="text-sm leading-6 text-slate-500 dark:text-slate-400">Simple, powerful APIs for developers who build the future.</p><div class="mt-5 flex items-center gap-2">${['Github','Twitter','Linkedin','Mail'].map((x) => `<button class="flex h-8 w-8 items-center justify-center rounded-lg border border-slate-200 text-slate-500 transition-colors hover:border-slate-300 hover:bg-slate-50 hover:text-slate-950 dark:border-slate-800 dark:text-slate-400 dark:hover:bg-slate-900 dark:hover:text-white">${icon(x,'h-3.5 w-3.5')}</button>`).join('')}</div></div><div class="grid grid-cols-2 gap-x-16 gap-y-8 sm:grid-cols-3"><div><h4 class="mb-4 text-xs font-bold uppercase tracking-wider text-slate-950 dark:text-white">Product</h4><div class="flex flex-col gap-3 text-sm text-slate-500 dark:text-slate-400"><button data-nav="/docs" class="text-left hover:text-cyan-600">Documentation</button><button class="text-left hover:text-cyan-600">Changelog</button><button class="text-left hover:text-cyan-600">Status</button></div></div><div><h4 class="mb-4 text-xs font-bold uppercase tracking-wider text-slate-950 dark:text-white">Resources</h4><div class="flex flex-col gap-3 text-sm text-slate-500 dark:text-slate-400"><button class="text-left hover:text-cyan-600">Examples</button><button class="text-left hover:text-cyan-600">SDKs</button><button class="text-left hover:text-cyan-600">Community</button></div></div><div><h4 class="mb-4 text-xs font-bold uppercase tracking-wider text-slate-950 dark:text-white">Company</h4><div class="flex flex-col gap-3 text-sm text-slate-500 dark:text-slate-400"><button class="text-left hover:text-cyan-600">About</button><button class="text-left hover:text-cyan-600">Contact</button><button class="text-left hover:text-cyan-600">Privacy</button></div></div></div></div><div class="mt-12 flex flex-col justify-between gap-3 border-t border-slate-100 pt-6 text-xs text-slate-400 dark:border-slate-800 sm:flex-row"><span>© 2024 SamApi. Built for developers.</span><span>Made with care for the developer community.</span></div></div></footer>`;
}

export function bindFooter() { document.querySelectorAll('footer [data-nav]').forEach((el) => el.addEventListener('click', () => navigate(el.dataset.nav))); }

export function apiIcon(api, size='md') {
  return icon(api.icon, size === 'sm' ? 'h-4 w-4' : size === 'lg' ? 'h-6 w-6' : 'h-5 w-5');
}

export function renderApiCard(api) {
  return `<div class="group flex flex-col rounded-2xl border border-slate-200 bg-white p-5 transition-all duration-300 hover:-translate-y-1 hover:border-slate-300 hover:shadow-xl hover:shadow-slate-200/60 dark:border-slate-800 dark:bg-slate-900/60 dark:hover:border-slate-700 dark:hover:shadow-black/20"><div class="mb-5 flex items-start justify-between"><div class="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200">${apiIcon(api)}</div><span class="rounded-md bg-cyan-50 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-cyan-700 dark:bg-cyan-950/40 dark:text-cyan-400">${esc(api.category)}</span></div><h3 class="mb-2 text-[16px] font-bold tracking-[-0.02em] text-slate-950 dark:text-white">${esc(api.name)}</h3><p class="mb-5 min-h-[48px] text-sm leading-6 text-slate-500 dark:text-slate-400">${esc(api.description)}</p><div class="mt-auto flex items-center justify-between border-t border-slate-100 pt-4 dark:border-slate-800"><div class="flex items-center gap-2"><span class="rounded-md px-1.5 py-1 text-[10px] font-bold ${api.method === 'GET' ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-400' : 'bg-amber-50 text-amber-700 dark:bg-amber-950/30 dark:text-amber-400'}">${esc(api.method)}</span><code class="text-xs text-slate-400">${esc(api.endpoint)}</code></div><button data-copy="${esc(BASE_URL+api.endpoint)}" class="copy-endpoint flex h-7 w-7 items-center justify-center rounded-md text-slate-400 transition-colors hover:bg-slate-100 hover:text-slate-950 dark:hover:bg-slate-800 dark:hover:text-white" aria-label="Copy endpoint">${icon('Copy','h-3.5 w-3.5')}</button></div><div class="mt-4 flex items-center gap-3"><button data-nav="/docs/${encodeURIComponent(api.slug)}" class="flex flex-1 items-center justify-center gap-2 rounded-lg bg-slate-950 py-2.5 text-xs font-semibold text-white transition-colors hover:bg-slate-700 dark:bg-white dark:text-slate-950 dark:hover:bg-slate-200">View docs ${icon('ArrowUpRight','h-3.5 w-3.5')}</button><button data-nav="/docs/${encodeURIComponent(api.slug)}?try=true" class="flex h-9 w-10 items-center justify-center rounded-lg border border-slate-200 text-slate-500 transition-colors hover:border-slate-300 hover:text-slate-950 dark:border-slate-700 dark:hover:border-slate-600 dark:hover:text-white" aria-label="Try API">${icon('Terminal','h-3.5 w-3.5')}</button></div></div>`;
}

export function bindApiCards() {
  document.querySelectorAll('[data-nav]').forEach((el) => el.addEventListener('click', () => navigate(el.dataset.nav)));
  document.querySelectorAll('[data-copy]').forEach((el) => el.addEventListener('click', async () => { await copyText(el.dataset.copy); const old=el.innerHTML; el.innerHTML=icon('Check','h-3.5 w-3.5 text-emerald-500'); refreshIcons(); setTimeout(()=>{el.innerHTML=old; refreshIcons();},1600); }));
}

export { apiDefinitions };
